### PR TITLE
New design for Home & Add Anime screens

### PR DESCRIPTION
**Pull request by ismaeldcom**
Hi @MaisaMilena,

I just make a quick design for **Home** and Add **Anime screens**, the last one with a modal approach. #5 

[InVision project](https://invis.io/AROFZLETWGU) with two screens, color palette, fonts and spacing used.

Quick preview:
screen shot 2018-10-07 at 21 33 22

I hope you like them ;)

### CODE REVIEW

**Comment by MaisaMilena** [comment]
😄 woooow! I'm really impressed by how you kept it simple, using the same elements that I used but so beautiful hahaha I really like it, thank you @ismaeldcom ! 

I've accessed the InVision link but I can't inspect the screen, to see the size of spacing and things like that. It is possible to adjust this?

This is an example of Inspect Mode:
image

**Comment by ismaeldcom** [comment]
I'm glad you liked it @MaisaMilena. I don't use InVision often, but I suppose that you need some privileges to be able to access that section, I've just sent you an invitation. Let me know if you still can't access inspect mode.

**Comment by MaisaMilena** [comment]
@ismaeldcom still can't have access but it's ok! Thank you so much for your contribution. When we finish the implementation can I show you and ask for your approval?

**Comment by ismaeldcom** [comment]
I send and invitation to maisa.******@*mail.com, it appear like pending. Anyway I can share the .sketch file if you want.

Of course, if I can help when the implementation is done, just tell me.

**Comment by MaisaMilena** [comment]
@ismaeldcom I received the invitation e-mail about 3 hours ago. It has the inspect mode! Hahaha, thank you again!

**Comment by MaisaMilena** [comment]
@ismaeldcom I just realized that there is a website called MyAnimeList, a big one hahaha but I didn't know about that. I made this project just for study and I wanted to let you know it, there is nothing to do with the website, ok? Sorry about this 😞

**Comment by ismaeldcom** [comment]
@MaisaMilena Wow! what a coincidence, I use the web and thought it was a project to demonstrate the use of VIP using MyAnimeList.net as many devs use Hacker News. I can make another design if you want, no problem.

**Comment by MaisaMilena** [comment]
you don't need to, I love your design, is just to let you know that I'm not related to the website hahaha

**Pull request merged**
